version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: winterfell-postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stairs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  temp-postgres:
    image: ankane/pgvector
    container_name: winterfell-temp-pg
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stairs_db
    volumes:
      - temp_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: winterfell-redis
    ports: 
      - "6379:6379"

volumes:
  postgres_data:
  temp_postgres_data:
